backend:
  name: github
  repo: JOHNBASS/blog-chatxbuy
  branch: main # Branch to update (optional; defaults to master)
  auth:
    clientId: Ov23liijRwtah6qkJY0i
    clientSecret: dc19ad54150f1102c194e7222d15bbff2c335f03

media_folder: public/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog' # label in admin
    folder: 'content/blog' # save blog in this folder
    format: 'frontmatter'
    create: true # allow create new blog in folder
    slug: '{{articleId}}-{{title}}'
    editor:
      preview: false
    fields:
      - { label: 'Article ID', name: 'articleId', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover', name: 'cover', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Pinned', name: 'pinned', widget: 'boolean' }